#!/bin/bash

APP_NAME=identiform

echo "Triger received. Deploying..."
cd "/opt/$APP_NAME"
git --git-dir="/opt/$APP_NAME.git" --work-tree="/opt/$APP_NAME" checkout master -f

echo 'Installing'
npm install

echo 'Building...'
npm run build
